if: sender = buildymcgee
dist: trusty
language: node_js
node_js: '9'
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
before_script:
- "./node_modules/.bin/brunch build --production"
- "sed -i.orig 's/build/docs/g' karma.conf.js"
after_success:
- "erb fateOfAllFools.prod.user.js.erb > fateOfAllFools.user.js"
- "./deploy.sh"
